project:
  title: "hmw_1_data_analysis"


format:
  html:
    theme: lux
    css: style.css
  ipynb:
    ipynb-ouput: all  # compute all cells when rendering a notebook

render: # which files to render
  - report.qmd


# output-dir: "outdir"

execute: 
  #eval: true
  #echo: false
  collapse: false
  cache: true  # cache the notebook, requires jupyter-cache
  daemon: true  # don't restart the kenel at each render



engine: jupyter

license: CC BY-NC

